
---

### 2) Discussion **Category Forms**  
Place these files under: **`.github/DISCUSSION_TEMPLATE/`**

> GitHub Discussion Forms use YAML. Each file defines a **form** and the **category** it belongs to. After pushing to `main`, configure matching **Discussion categories** in your repo settings with the exact names used below.

#### `.github/DISCUSSION_TEMPLATE/q-a.yml`
```yaml
# Q&A (how-to and troubleshooting questions)
title: "Q&A: {short question here}"
labels:
  - q&a
discussion_category_name: "Q&A"
body:
  - type: markdown
    attributes:
      value: |
        Ask clear, specific questions. Include AEON version, posture, and any commands run.
  - type: input
    id: aeon_version
    attributes:
      label: AEON.json version
      placeholder: e.g., v3.6
  - type: dropdown
    id: posture
    attributes:
      label: Current posture (from `show status`)
      options:
        - Curtain: drawn, Enigma: disabled
        - Curtain: lifted, Enigma: shadow
        - Curtain: lifted, Enigma: full
        - Unknown / not sure
  - type: textarea
    id: details
    attributes:
      label: Question details
      description: What did you expect vs what happened?
  - type: textarea
    id: evidence
    attributes:
      label: Evidence (optional)
      description: Paste redacted output (audit/trace snippets, error text)
      render: text
