# Demos and results
title: "Show & Tell: {demo name}"
labels:
  - showcase
discussion_category_name: "Show & Tell"
body:
  - type: markdown
    attributes:
      value: |
        Share a demo, prompt, or result. Screenshots welcome.
  - type: input
    id: context
    attributes:
      label: Context (what problem did you solve?)
  - type: textarea
    id: method
    attributes:
      label: Method (commands, posture, modules)
      placeholder: e.g., lift curtain → enable enigma (shadow) → trace show 5
  - type: textarea
    id: result
    attributes:
      label: Result
      placeholder: What happened? What’s interesting?
  - type: textarea
    id: artifacts
    attributes:
      label: Artifacts (optional)
      description: Paste links or short snippets (redact sensitive data)
